// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Schema for creating a new country
 */
export type CountryCreate = {
    /**
     * Country name
     */
    name: string;
    /**
     * ISO country code (3 letters)
     */
    code: string;
    /**
     * Whether country is active
     */
    is_active?: boolean;
};

/**
 * Detailed country response with all fields
 */
export type CountryDetailPublic = {
    /**
     * Country name
     */
    name: string;
    /**
     * ISO country code (3 letters)
     */
    code: string;
    /**
     * Whether country is active
     */
    is_active?: boolean;
    id: string;
};

/**
 * Schema for updating a country (all fields optional)
 */
export type CountryUpdate = {
    name?: (string | null);
    code?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a new district
 */
export type DistrictCreate = {
    /**
     * District name
     */
    name: string;
    /**
     * District code
     */
    code?: (string | null);
    /**
     * Whether district is active
     */
    is_active?: boolean;
    /**
     * State ID this district belongs to
     */
    state_id: string;
};

/**
 * Detailed district response with all fields
 */
export type DistrictDetailPublic = {
    /**
     * District name
     */
    name: string;
    /**
     * District code
     */
    code?: (string | null);
    /**
     * Whether district is active
     */
    is_active?: boolean;
    id: string;
    state_id: string;
};

/**
 * Schema for updating a district (all fields optional)
 */
export type DistrictUpdate = {
    name?: (string | null);
    code?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Detailed gender response with all fields.
 */
export type GenderDetailPublic = {
    id: string;
    /**
     * Gender name
     */
    name: string;
    /**
     * Gender code
     */
    code: string;
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether gender is active
     */
    is_active?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Enum for ticket status.
 */
export type IssueStatus = 'open' | 'closed';

/**
 * Enum for ticket types.
 */
export type IssueType = 'bug' | 'feature_request';

/**
 * Properties to receive on item creation
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Properties to return via API
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

/**
 * List of items response
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * Properties to receive on item update
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Schema for creating a new locality
 */
export type LocalityCreate = {
    /**
     * Locality/Village name
     */
    name: string;
    /**
     * Locality code
     */
    code?: (string | null);
    /**
     * Whether locality is active
     */
    is_active?: boolean;
    /**
     * Sub-district ID this locality belongs to
     */
    sub_district_id: string;
};

/**
 * Detailed locality response with all fields
 */
export type LocalityDetailPublic = {
    /**
     * Locality/Village name
     */
    name: string;
    /**
     * Locality code
     */
    code?: (string | null);
    /**
     * Whether locality is active
     */
    is_active?: boolean;
    id: string;
    sub_district_id: string;
};

/**
 * Schema for updating a locality (all fields optional)
 */
export type LocalityUpdate = {
    name?: (string | null);
    code?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Generic message response
 */
export type Message = {
    message: string;
};

/**
 * Password reset request
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for creating a new person address.
 */
export type PersonAddressCreate = {
    /**
     * Country reference
     */
    country_id: string;
    /**
     * State reference
     */
    state_id?: (string | null);
    /**
     * District reference
     */
    district_id?: (string | null);
    /**
     * Sub-district reference
     */
    sub_district_id?: (string | null);
    /**
     * Locality reference
     */
    locality_id?: (string | null);
    /**
     * Additional address details
     */
    address_line?: (string | null);
    /**
     * Address start date
     */
    start_date: string;
    /**
     * Address end date
     */
    end_date?: (string | null);
    /**
     * Is this the current address
     */
    is_current?: boolean;
};

/**
 * Address details with resolved location names.
 */
export type PersonAddressDetails = {
    locality_name?: (string | null);
    sub_district_name?: (string | null);
    district_name?: (string | null);
    state_name?: (string | null);
    country_name: string;
    address_line?: (string | null);
};

/**
 * Person address response schema.
 */
export type PersonAddressPublic = {
    /**
     * Country reference
     */
    country_id: string;
    /**
     * State reference
     */
    state_id?: (string | null);
    /**
     * District reference
     */
    district_id?: (string | null);
    /**
     * Sub-district reference
     */
    sub_district_id?: (string | null);
    /**
     * Locality reference
     */
    locality_id?: (string | null);
    /**
     * Additional address details
     */
    address_line?: (string | null);
    /**
     * Address start date
     */
    start_date: string;
    /**
     * Address end date
     */
    end_date?: (string | null);
    /**
     * Is this the current address
     */
    is_current?: boolean;
    id: string;
    person_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating a person address (all fields optional).
 */
export type PersonAddressUpdate = {
    country_id?: (string | null);
    state_id?: (string | null);
    district_id?: (string | null);
    sub_district_id?: (string | null);
    locality_id?: (string | null);
    address_line?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_current?: (boolean | null);
};

/**
 * Complete person details with resolved names.
 */
export type PersonCompleteDetailsResponse = {
    id: string;
    first_name: string;
    middle_name?: (string | null);
    last_name: string;
    date_of_birth: string;
    date_of_death?: (string | null);
    gender_name: string;
    address?: (PersonAddressDetails | null);
    religion?: (PersonReligionDetails | null);
};

/**
 * Schema for person contribution with statistics.
 */
export type PersonContributionPublic = {
    /**
     * Person ID
     */
    id: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Date of birth
     */
    date_of_birth: string;
    /**
     * Date of death
     */
    date_of_death?: (string | null);
    /**
     * Whether the person is active
     */
    is_active: boolean;
    /**
     * Formatted address string
     */
    address: string;
    /**
     * Total profile view count
     */
    total_views: number;
    /**
     * Record creation timestamp
     */
    created_at: string;
};

/**
 * Schema for creating a new person.
 */
export type PersonCreate = {
    /**
     * First name
     */
    first_name: string;
    /**
     * Middle name
     */
    middle_name?: (string | null);
    /**
     * Last name
     */
    last_name: string;
    /**
     * Gender reference
     */
    gender_id: string;
    /**
     * Date of birth
     */
    date_of_birth: string;
    /**
     * Date of death
     */
    date_of_death?: (string | null);
    /**
     * User account reference (optional for family members)
     */
    user_id?: (string | null);
    /**
     * Is this the primary person for the user
     */
    is_primary?: boolean;
};

/**
 * Person details for relationship response.
 */
export type PersonDetails = {
    id: string;
    first_name: string;
    middle_name?: (string | null);
    last_name: string;
    gender_id: string;
    date_of_birth: string;
    date_of_death?: (string | null);
    user_id?: (string | null);
    created_by_user_id: string;
    is_primary: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Result of family member discovery.
 *
 * Represents a person who is connected to the user's family members
 * but not yet directly connected to the user, along with metadata
 * about the inferred relationship and connection path.
 */
export type PersonDiscoveryResult = {
    /**
     * Person ID
     */
    person_id: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Middle name
     */
    middle_name?: (string | null);
    /**
     * Last name
     */
    last_name: string;
    /**
     * Date of birth
     */
    date_of_birth: string;
    /**
     * Date of death
     */
    date_of_death?: (string | null);
    /**
     * Gender ID
     */
    gender_id: string;
    /**
     * Comma-separated address display string
     */
    address_display?: (string | null);
    /**
     * Comma-separated religion display string
     */
    religion_display?: (string | null);
    /**
     * Relationship type ID (e.g., 'rel-6a0ede824d104' for Son)
     */
    inferred_relationship_type: string;
    /**
     * Human-readable relationship label (e.g., 'Son', 'Daughter')
     */
    inferred_relationship_label: string;
    /**
     * Human-readable explanation of connection (e.g., 'Connected to your spouse Maria Garcia')
     */
    connection_path: string;
    /**
     * Relationship proximity (1 = direct connection, 2 = 2 degrees, etc.)
     */
    proximity_score: number;
    /**
     * Relationship type priority (1 = children, 2 = parents, 3 = spouses)
     */
    relationship_priority: number;
};

/**
 * Result schema for person match.
 */
export type PersonMatchResult = {
    /**
     * Person ID
     */
    person_id: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Middle name
     */
    middle_name?: (string | null);
    /**
     * Last name
     */
    last_name: string;
    /**
     * Date of birth
     */
    date_of_birth: string;
    /**
     * Date of death
     */
    date_of_death?: (string | null);
    /**
     * Comma-separated address display
     */
    address_display: string;
    /**
     * Comma-separated religion display
     */
    religion_display: string;
    /**
     * Overall match score 0-100
     */
    match_score: number;
    /**
     * Name similarity score 0-100
     */
    name_match_score: number;
    /**
     * True if this is the current user's person record
     */
    is_current_user?: boolean;
    /**
     * True if this person is already connected to the current user
     */
    is_already_connected?: boolean;
};

/**
 * Schema for creating person metadata.
 */
export type PersonMetadataCreate = {
    /**
     * Profile image URL
     */
    profile_image_url?: (string | null);
    /**
     * Person biography
     */
    bio?: (string | null);
};

/**
 * Person metadata response schema.
 */
export type PersonMetadataPublic = {
    /**
     * Profile image URL
     */
    profile_image_url?: (string | null);
    /**
     * Person biography
     */
    bio?: (string | null);
    id: string;
    person_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating person metadata (all fields optional).
 */
export type PersonMetadataUpdate = {
    profile_image_url?: (string | null);
    bio?: (string | null);
};

/**
 * Schema for creating a new person profession.
 */
export type PersonProfessionCreate = {
    /**
     * Profession reference
     */
    profession_id: string;
    /**
     * Profession start date
     */
    start_date: string;
    /**
     * Profession end date
     */
    end_date?: (string | null);
    /**
     * Is this the current profession
     */
    is_current?: boolean;
};

/**
 * Person profession response schema.
 */
export type PersonProfessionPublic = {
    /**
     * Profession reference
     */
    profession_id: string;
    /**
     * Profession start date
     */
    start_date: string;
    /**
     * Profession end date
     */
    end_date?: (string | null);
    /**
     * Is this the current profession
     */
    is_current?: boolean;
    id: string;
    person_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating a person profession (all fields optional).
 */
export type PersonProfessionUpdate = {
    profession_id?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_current?: (boolean | null);
};

/**
 * Person response schema.
 */
export type PersonPublic = {
    /**
     * First name
     */
    first_name: string;
    /**
     * Middle name
     */
    middle_name?: (string | null);
    /**
     * Last name
     */
    last_name: string;
    /**
     * Gender reference
     */
    gender_id: string;
    /**
     * Date of birth
     */
    date_of_birth: string;
    /**
     * Date of death
     */
    date_of_death?: (string | null);
    id: string;
    user_id: (string | null);
    created_by_user_id: string;
    is_primary: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for creating a new person relationship.
 */
export type PersonRelationshipCreate = {
    /**
     * Related person reference
     */
    related_person_id: string;
    /**
     * Relationship type
     */
    relationship_type: RelationshipType;
    /**
     * Relationship start date
     */
    start_date?: (string | null);
    /**
     * Relationship end date
     */
    end_date?: (string | null);
    /**
     * Is relationship active
     */
    is_active?: boolean;
};

/**
 * Person relationship response schema.
 */
export type PersonRelationshipPublic = {
    /**
     * Related person reference
     */
    related_person_id: string;
    /**
     * Relationship type
     */
    relationship_type: RelationshipType;
    /**
     * Relationship start date
     */
    start_date?: (string | null);
    /**
     * Relationship end date
     */
    end_date?: (string | null);
    /**
     * Is relationship active
     */
    is_active?: boolean;
    id: string;
    person_id: string;
    created_at: string;
    updated_at: string;
    /**
     * Get human-readable label for the relationship type.
     */
    readonly relationship_type_label: string;
};

/**
 * Response containing selected person and their relationships.
 */
export type PersonRelationshipsWithDetailsResponse = {
    selected_person: PersonDetails;
    relationships: Array<PersonRelationshipWithDetails>;
};

/**
 * Schema for updating a person relationship (all fields optional).
 */
export type PersonRelationshipUpdate = {
    related_person_id?: (string | null);
    relationship_type?: (RelationshipType | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Person relationship with full person details.
 */
export type PersonRelationshipWithDetails = {
    relationship: PersonRelationshipPublic;
    person: PersonDetails;
};

/**
 * Schema for creating person religion.
 */
export type PersonReligionCreate = {
    /**
     * Religion reference
     */
    religion_id: string;
    /**
     * Religion category reference
     */
    religion_category_id?: (string | null);
    /**
     * Religion sub-category reference
     */
    religion_sub_category_id?: (string | null);
};

/**
 * Religion details with resolved names.
 */
export type PersonReligionDetails = {
    religion_name: string;
    category_name?: (string | null);
    sub_category_name?: (string | null);
};

/**
 * Person religion response schema.
 */
export type PersonReligionPublic = {
    /**
     * Religion reference
     */
    religion_id: string;
    /**
     * Religion category reference
     */
    religion_category_id?: (string | null);
    /**
     * Religion sub-category reference
     */
    religion_sub_category_id?: (string | null);
    id: string;
    person_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating person religion (all fields optional).
 */
export type PersonReligionUpdate = {
    religion_id?: (string | null);
    religion_category_id?: (string | null);
    religion_sub_category_id?: (string | null);
};

/**
 * Request schema for person matching search.
 */
export type PersonSearchRequest = {
    /**
     * First name to search
     */
    first_name: string;
    /**
     * Last name to search
     */
    last_name: string;
    /**
     * Middle name (optional)
     */
    middle_name?: (string | null);
    /**
     * Gender ID (optional)
     */
    gender_id?: (string | null);
    /**
     * Date of birth (optional)
     */
    date_of_birth?: (string | null);
    /**
     * Country reference
     */
    country_id: string;
    /**
     * State reference
     */
    state_id: string;
    /**
     * District reference
     */
    district_id: string;
    /**
     * Sub-district reference (optional)
     */
    sub_district_id?: (string | null);
    /**
     * Locality reference (optional)
     */
    locality_id?: (string | null);
    /**
     * Religion reference
     */
    religion_id: string;
    /**
     * Religion category reference (optional)
     */
    religion_category_id?: (string | null);
    /**
     * Religion sub-category reference (optional)
     */
    religion_sub_category_id?: (string | null);
    /**
     * Comma-separated address display string (optional)
     */
    address_display?: (string | null);
    /**
     * Comma-separated religion display string (optional)
     */
    religion_display?: (string | null);
};

/**
 * Schema for updating a person (all fields optional).
 */
export type PersonUpdate = {
    first_name?: (string | null);
    middle_name?: (string | null);
    last_name?: (string | null);
    gender_id?: (string | null);
    date_of_birth?: (string | null);
    date_of_death?: (string | null);
    religion_id?: (string | null);
    religion_category_id?: (string | null);
    religion_sub_category_id?: (string | null);
};

/**
 * Schema for creating a new post.
 */
export type PostCreate = {
    /**
     * Post title
     */
    title: string;
    /**
     * Post content
     */
    content: string;
    /**
     * Whether post is published
     */
    is_published?: boolean;
};

/**
 * Post response schema.
 */
export type PostPublic = {
    /**
     * Post title
     */
    title: string;
    /**
     * Post content
     */
    content: string;
    /**
     * Whether post is published
     */
    is_published?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * List of posts response.
 */
export type PostsPublic = {
    data: Array<PostPublic>;
    count: number;
};

/**
 * Schema for updating a post (all fields optional).
 */
export type PostUpdate = {
    title?: (string | null);
    content?: (string | null);
    is_published?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new profession.
 */
export type ProfessionCreate = {
    /**
     * Profession name
     */
    name: string;
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Weight for sorting/priority
     */
    weight?: number;
    /**
     * Whether profession is active
     */
    is_active?: boolean;
};

/**
 * Detailed profession response with all fields.
 */
export type ProfessionDetailPublic = {
    /**
     * Profession name
     */
    name: string;
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Weight for sorting/priority
     */
    weight?: number;
    /**
     * Whether profession is active
     */
    is_active?: boolean;
    id: string;
};

/**
 * Schema for updating a profession (all fields optional).
 */
export type ProfessionUpdate = {
    name?: (string | null);
    description?: (string | null);
    weight?: (number | null);
    is_active?: (boolean | null);
};

/**
 * Profile completion status response.
 */
export type ProfileCompletionStatus = {
    is_complete: boolean;
    has_person: boolean;
    has_address: boolean;
    has_religion: boolean;
    missing_fields: Array<(string)>;
};

/**
 * Relationship types between persons with unique identifiers.
 */
export type RelationshipType = 'rel-6a0ede824d101' | 'rel-6a0ede824d102' | 'rel-6a0ede824d103' | 'rel-6a0ede824d104' | 'rel-6a0ede824d105' | 'rel-6a0ede824d106' | 'rel-6a0ede824d107';

/**
 * Schema for creating a new religion category.
 */
export type ReligionCategoryCreate = {
    /**
     * Category name (e.g., Caste, Sect, Denomination)
     */
    name: string;
    /**
     * Category code
     */
    code?: (string | null);
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether category is active
     */
    is_active?: boolean;
    /**
     * Religion ID this category belongs to
     */
    religion_id: string;
};

/**
 * Detailed religion category response with all fields.
 */
export type ReligionCategoryDetailPublic = {
    /**
     * Category name (e.g., Caste, Sect, Denomination)
     */
    name: string;
    /**
     * Category code
     */
    code?: (string | null);
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether category is active
     */
    is_active?: boolean;
    id: string;
    religion_id: string;
};

/**
 * Schema for updating a religion category (all fields optional).
 */
export type ReligionCategoryUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a new religion.
 */
export type ReligionCreate = {
    /**
     * Religion name
     */
    name: string;
    /**
     * Religion code
     */
    code: string;
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether religion is active
     */
    is_active?: boolean;
};

/**
 * Detailed religion response with all fields.
 */
export type ReligionDetailPublic = {
    /**
     * Religion name
     */
    name: string;
    /**
     * Religion code
     */
    code: string;
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether religion is active
     */
    is_active?: boolean;
    id: string;
};

/**
 * Schema for creating a new religion sub-category.
 */
export type ReligionSubCategoryCreate = {
    /**
     * Sub-category name (e.g., Sub-caste, Sub-sect)
     */
    name: string;
    /**
     * Sub-category code
     */
    code?: (string | null);
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether sub-category is active
     */
    is_active?: boolean;
    /**
     * Category ID this sub-category belongs to
     */
    category_id: string;
};

/**
 * Detailed religion sub-category response with all fields.
 */
export type ReligionSubCategoryDetailPublic = {
    /**
     * Sub-category name (e.g., Sub-caste, Sub-sect)
     */
    name: string;
    /**
     * Sub-category code
     */
    code?: (string | null);
    /**
     * Optional description
     */
    description?: (string | null);
    /**
     * Whether sub-category is active
     */
    is_active?: boolean;
    id: string;
    category_id: string;
};

/**
 * Schema for updating a religion sub-category (all fields optional).
 */
export type ReligionSubCategoryUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for updating a religion (all fields optional).
 */
export type ReligionUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a new state
 */
export type StateCreate = {
    /**
     * State name
     */
    name: string;
    /**
     * State code
     */
    code?: (string | null);
    /**
     * Whether state is active
     */
    is_active?: boolean;
    /**
     * Country ID this state belongs to
     */
    country_id: string;
};

/**
 * Detailed state response with all fields
 */
export type StateDetailPublic = {
    /**
     * State name
     */
    name: string;
    /**
     * State code
     */
    code?: (string | null);
    /**
     * Whether state is active
     */
    is_active?: boolean;
    id: string;
    country_id: string;
};

/**
 * Schema for updating a state (all fields optional)
 */
export type StateUpdate = {
    name?: (string | null);
    code?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a new sub-district
 */
export type SubDistrictCreate = {
    /**
     * Sub-district/Tehsil name
     */
    name: string;
    /**
     * Sub-district code
     */
    code?: (string | null);
    /**
     * Whether sub-district is active
     */
    is_active?: boolean;
    /**
     * District ID this sub-district belongs to
     */
    district_id: string;
};

/**
 * Detailed sub-district response with all fields
 */
export type SubDistrictDetailPublic = {
    /**
     * Sub-district/Tehsil name
     */
    name: string;
    /**
     * Sub-district code
     */
    code?: (string | null);
    /**
     * Whether sub-district is active
     */
    is_active?: boolean;
    id: string;
    district_id: string;
};

/**
 * Schema for updating a sub-district (all fields optional)
 */
export type SubDistrictUpdate = {
    name?: (string | null);
    code?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a new support ticket.
 */
export type SupportTicketCreate = {
    /**
     * Type of issue: bug or feature_request
     */
    issue_type: IssueType;
    /**
     * Ticket title (max 100 characters)
     */
    title: string;
    /**
     * Detailed description (max 2000 characters)
     */
    description: string;
};

/**
 * Support ticket response schema.
 */
export type SupportTicketPublic = {
    id: string;
    user_id: string;
    issue_type: IssueType;
    title: string;
    description: string;
    status: IssueStatus;
    resolved_by_user_id: (string | null);
    resolved_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Support ticket response schema with user details (for admin view).
 */
export type SupportTicketPublicWithUser = {
    id: string;
    user_id: string;
    issue_type: IssueType;
    title: string;
    description: string;
    status: IssueStatus;
    resolved_by_user_id: (string | null);
    resolved_at: (string | null);
    created_at: string;
    updated_at: string;
    /**
     * Email of the user who created the ticket
     */
    user_email: string;
    /**
     * Full name of the user who created the ticket
     */
    user_full_name?: (string | null);
    /**
     * Email of the admin who resolved the ticket
     */
    resolved_by_email?: (string | null);
};

/**
 * List of support tickets response.
 */
export type SupportTicketsPublic = {
    data: Array<SupportTicketPublic>;
    count: number;
};

/**
 * Schema for updating a support ticket (all fields optional).
 */
export type SupportTicketUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * JSON payload containing access token
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Password update request
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Properties to receive via API on creation
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

/**
 * Properties to return via API
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    is_superuser?: boolean;
};

/**
 * Properties for user self-registration
 */
export type UserRegister = {
    first_name: string;
    middle_name?: (string | null);
    last_name: string;
    /**
     * Gender: MALE or FEMALE
     */
    gender: string;
    /**
     * Date of birth in YYYY-MM-DD format
     */
    date_of_birth: string;
    email: string;
    password: string;
};

/**
 * User role levels with hierarchical permissions.
 *
 * Hierarchy: ADMIN > SUPERUSER > USER
 * Higher roles inherit all permissions from lower roles.
 */
export type UserRole = 'user' | 'superuser' | 'admin';

/**
 * Schema for updating user role (admin only)
 */
export type UserRoleUpdate = {
    role: UserRole;
};

/**
 * List of users response
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Properties to receive via API on update, all are optional
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Properties for user self-update
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AddressMetadataGetCountriesResponse = (unknown);

export type AddressMetadataCreateCountryData = {
    requestBody: CountryCreate;
};

export type AddressMetadataCreateCountryResponse = (CountryDetailPublic);

export type AddressMetadataGetCountryByIdData = {
    countryId: string;
};

export type AddressMetadataGetCountryByIdResponse = (CountryDetailPublic);

export type AddressMetadataUpdateCountryData = {
    countryId: string;
    requestBody: CountryUpdate;
};

export type AddressMetadataUpdateCountryResponse = (CountryDetailPublic);

export type AddressMetadataDeleteCountryData = {
    countryId: string;
};

export type AddressMetadataDeleteCountryResponse = (unknown);

export type AddressMetadataGetStatesByCountryData = {
    countryId: string;
};

export type AddressMetadataGetStatesByCountryResponse = (unknown);

export type AddressMetadataGetStateByIdData = {
    stateId: string;
};

export type AddressMetadataGetStateByIdResponse = (StateDetailPublic);

export type AddressMetadataUpdateStateData = {
    requestBody: StateUpdate;
    stateId: string;
};

export type AddressMetadataUpdateStateResponse = (StateDetailPublic);

export type AddressMetadataDeleteStateData = {
    stateId: string;
};

export type AddressMetadataDeleteStateResponse = (unknown);

export type AddressMetadataCreateStateData = {
    requestBody: StateCreate;
};

export type AddressMetadataCreateStateResponse = (StateDetailPublic);

export type AddressMetadataGetDistrictsByStateData = {
    stateId: string;
};

export type AddressMetadataGetDistrictsByStateResponse = (unknown);

export type AddressMetadataGetDistrictByIdData = {
    districtId: string;
};

export type AddressMetadataGetDistrictByIdResponse = (DistrictDetailPublic);

export type AddressMetadataUpdateDistrictData = {
    districtId: string;
    requestBody: DistrictUpdate;
};

export type AddressMetadataUpdateDistrictResponse = (DistrictDetailPublic);

export type AddressMetadataDeleteDistrictData = {
    districtId: string;
};

export type AddressMetadataDeleteDistrictResponse = (unknown);

export type AddressMetadataCreateDistrictData = {
    requestBody: DistrictCreate;
};

export type AddressMetadataCreateDistrictResponse = (DistrictDetailPublic);

export type AddressMetadataGetSubDistrictsByDistrictData = {
    districtId: string;
};

export type AddressMetadataGetSubDistrictsByDistrictResponse = (unknown);

export type AddressMetadataGetSubDistrictByIdData = {
    subDistrictId: string;
};

export type AddressMetadataGetSubDistrictByIdResponse = (SubDistrictDetailPublic);

export type AddressMetadataUpdateSubDistrictData = {
    requestBody: SubDistrictUpdate;
    subDistrictId: string;
};

export type AddressMetadataUpdateSubDistrictResponse = (SubDistrictDetailPublic);

export type AddressMetadataDeleteSubDistrictData = {
    subDistrictId: string;
};

export type AddressMetadataDeleteSubDistrictResponse = (unknown);

export type AddressMetadataCreateSubDistrictData = {
    requestBody: SubDistrictCreate;
};

export type AddressMetadataCreateSubDistrictResponse = (SubDistrictDetailPublic);

export type AddressMetadataGetLocalitiesBySubDistrictData = {
    subDistrictId: string;
};

export type AddressMetadataGetLocalitiesBySubDistrictResponse = (unknown);

export type AddressMetadataGetLocalityByIdData = {
    localityId: string;
};

export type AddressMetadataGetLocalityByIdResponse = (LocalityDetailPublic);

export type AddressMetadataUpdateLocalityData = {
    localityId: string;
    requestBody: LocalityUpdate;
};

export type AddressMetadataUpdateLocalityResponse = (LocalityDetailPublic);

export type AddressMetadataDeleteLocalityData = {
    localityId: string;
};

export type AddressMetadataDeleteLocalityResponse = (unknown);

export type AddressMetadataCreateLocalityData = {
    requestBody: LocalityCreate;
};

export type AddressMetadataCreateLocalityResponse = (LocalityDetailPublic);

export type IssuesCreateSupportTicketData = {
    requestBody: SupportTicketCreate;
};

export type IssuesCreateSupportTicketResponse = (SupportTicketPublic);

export type IssuesGetMySupportTicketsData = {
    limit?: number;
    skip?: number;
    status?: (IssueStatus | null);
};

export type IssuesGetMySupportTicketsResponse = (SupportTicketsPublic);

export type IssuesGetSupportTicketData = {
    supportTicketId: string;
};

export type IssuesGetSupportTicketResponse = (SupportTicketPublic);

export type IssuesUpdateSupportTicketData = {
    requestBody: SupportTicketUpdate;
    supportTicketId: string;
};

export type IssuesUpdateSupportTicketResponse = (SupportTicketPublic);

export type IssuesDeleteSupportTicketData = {
    supportTicketId: string;
};

export type IssuesDeleteSupportTicketResponse = (Message);

export type IssuesGetAllSupportTicketsAdminData = {
    issueType?: (IssueType | null);
    limit?: number;
    skip?: number;
    status?: (IssueStatus | null);
};

export type IssuesGetAllSupportTicketsAdminResponse = (Array<SupportTicketPublicWithUser>);

export type IssuesResolveSupportTicketData = {
    supportTicketId: string;
};

export type IssuesResolveSupportTicketResponse = (SupportTicketPublic);

export type IssuesReopenSupportTicketData = {
    supportTicketId: string;
};

export type IssuesReopenSupportTicketResponse = (SupportTicketPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PersonGetMyPersonResponse = (PersonPublic);

export type PersonCreateMyPersonData = {
    requestBody: PersonCreate;
};

export type PersonCreateMyPersonResponse = (PersonPublic);

export type PersonDeleteMyPersonResponse = (unknown);

export type PersonUpdateMyPersonData = {
    requestBody: PersonUpdate;
};

export type PersonUpdateMyPersonResponse = (PersonPublic);

export type PersonGetMyContributionsResponse = (Array<PersonContributionPublic>);

export type PersonCreateFamilyMemberData = {
    requestBody: PersonCreate;
};

export type PersonCreateFamilyMemberResponse = (PersonPublic);

export type PersonSearchMatchingPersonsData = {
    requestBody: PersonSearchRequest;
};

export type PersonSearchMatchingPersonsResponse = (Array<PersonMatchResult>);

export type PersonDiscoverFamilyMembersResponse = (Array<PersonDiscoveryResult>);

export type PersonCreatePersonAddressData = {
    personId: string;
    requestBody: PersonAddressCreate;
};

export type PersonCreatePersonAddressResponse = (PersonAddressPublic);

export type PersonCreatePersonReligionData = {
    personId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type PersonCreatePersonReligionResponse = (PersonPublic);

export type PersonGetPersonByUserIdData = {
    userId: string;
};

export type PersonGetPersonByUserIdResponse = (PersonPublic);

export type PersonDeletePersonByUserIdData = {
    userId: string;
};

export type PersonDeletePersonByUserIdResponse = (unknown);

export type PersonGetMyAddressesResponse = (Array<PersonAddressPublic>);

export type PersonCreateMyAddressData = {
    requestBody: PersonAddressCreate;
};

export type PersonCreateMyAddressResponse = (PersonAddressPublic);

export type PersonGetMyAddressData = {
    addressId: string;
};

export type PersonGetMyAddressResponse = (PersonAddressPublic);

export type PersonUpdateMyAddressData = {
    addressId: string;
    requestBody: PersonAddressUpdate;
};

export type PersonUpdateMyAddressResponse = (PersonAddressPublic);

export type PersonDeleteMyAddressData = {
    addressId: string;
};

export type PersonDeleteMyAddressResponse = (unknown);

export type PersonGetMyProfessionsResponse = (Array<PersonProfessionPublic>);

export type PersonCreateMyProfessionData = {
    requestBody: PersonProfessionCreate;
};

export type PersonCreateMyProfessionResponse = (PersonProfessionPublic);

export type PersonGetMyProfessionData = {
    professionId: string;
};

export type PersonGetMyProfessionResponse = (PersonProfessionPublic);

export type PersonUpdateMyProfessionData = {
    professionId: string;
    requestBody: PersonProfessionUpdate;
};

export type PersonUpdateMyProfessionResponse = (PersonProfessionPublic);

export type PersonDeleteMyProfessionData = {
    professionId: string;
};

export type PersonDeleteMyProfessionResponse = (unknown);

export type PersonGetMyRelationshipsResponse = (Array<PersonRelationshipPublic>);

export type PersonCreateMyRelationshipData = {
    requestBody: PersonRelationshipCreate;
};

export type PersonCreateMyRelationshipResponse = (PersonRelationshipPublic);

export type PersonGetMyRelationshipsWithDetailsResponse = (PersonRelationshipsWithDetailsResponse);

export type PersonGetPersonRelationshipsWithDetailsData = {
    personId: string;
};

export type PersonGetPersonRelationshipsWithDetailsResponse = (PersonRelationshipsWithDetailsResponse);

export type PersonGetPersonCompleteDetailsData = {
    personId: string;
};

export type PersonGetPersonCompleteDetailsResponse = (PersonCompleteDetailsResponse);

export type PersonGetMyRelationshipData = {
    relationshipId: string;
};

export type PersonGetMyRelationshipResponse = (PersonRelationshipPublic);

export type PersonUpdateMyRelationshipData = {
    relationshipId: string;
    requestBody: PersonRelationshipUpdate;
};

export type PersonUpdateMyRelationshipResponse = (PersonRelationshipPublic);

export type PersonDeleteMyRelationshipData = {
    relationshipId: string;
};

export type PersonDeleteMyRelationshipResponse = (unknown);

export type PersonGetMyMetadataResponse = (PersonMetadataPublic);

export type PersonCreateMyMetadataData = {
    requestBody: PersonMetadataCreate;
};

export type PersonCreateMyMetadataResponse = (PersonMetadataPublic);

export type PersonDeleteMyMetadataResponse = (unknown);

export type PersonUpdateMyMetadataData = {
    requestBody: PersonMetadataUpdate;
};

export type PersonUpdateMyMetadataResponse = (PersonMetadataPublic);

export type PersonMetadataGetProfessionsResponse = (unknown);

export type PersonMetadataCreateProfessionData = {
    requestBody: ProfessionCreate;
};

export type PersonMetadataCreateProfessionResponse = (ProfessionDetailPublic);

export type PersonMetadataGetProfessionByIdData = {
    professionId: string;
};

export type PersonMetadataGetProfessionByIdResponse = (ProfessionDetailPublic);

export type PersonMetadataUpdateProfessionData = {
    professionId: string;
    requestBody: ProfessionUpdate;
};

export type PersonMetadataUpdateProfessionResponse = (ProfessionDetailPublic);

export type PersonMetadataDeleteProfessionData = {
    professionId: string;
};

export type PersonMetadataDeleteProfessionResponse = (unknown);

export type PersonMetadataGetGendersResponse = (unknown);

export type PersonMetadataGetGenderByIdData = {
    genderId: string;
};

export type PersonMetadataGetGenderByIdResponse = (GenderDetailPublic);

export type PersonReligionCreateMyReligionData = {
    requestBody: PersonReligionCreate;
};

export type PersonReligionCreateMyReligionResponse = (PersonReligionPublic);

export type PersonReligionGetMyReligionResponse = (PersonReligionPublic);

export type PersonReligionUpdateMyReligionData = {
    requestBody: PersonReligionUpdate;
};

export type PersonReligionUpdateMyReligionResponse = (PersonReligionPublic);

export type PersonReligionDeleteMyReligionResponse = (void);

export type PostsGetPublishedPostsData = {
    limit?: number;
    skip?: number;
};

export type PostsGetPublishedPostsResponse = (PostsPublic);

export type PostsCreatePostData = {
    requestBody: PostCreate;
};

export type PostsCreatePostResponse = (PostPublic);

export type PostsGetMyPostsData = {
    limit?: number;
    skip?: number;
};

export type PostsGetMyPostsResponse = (PostsPublic);

export type PostsGetPostData = {
    postId: string;
};

export type PostsGetPostResponse = (PostPublic);

export type PostsUpdatePostData = {
    postId: string;
    requestBody: PostUpdate;
};

export type PostsUpdatePostResponse = (PostPublic);

export type PostsDeletePostData = {
    postId: string;
};

export type PostsDeletePostResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfileGetProfileCompletionStatusResponse = (ProfileCompletionStatus);

export type RelativesGetParentsData = {
    userId: string;
};

export type RelativesGetParentsResponse = (Array<PersonRelationshipPublic>);

export type RelativesGetChildrenData = {
    userId: string;
};

export type RelativesGetChildrenResponse = (Array<PersonRelationshipPublic>);

export type RelativesGetSpousesData = {
    userId: string;
};

export type RelativesGetSpousesResponse = (Array<PersonRelationshipPublic>);

export type RelativesGetSiblingsData = {
    userId: string;
};

export type RelativesGetSiblingsResponse = (Array<PersonRelationshipPublic>);

export type ReligionMetadataGetReligionsResponse = (unknown);

export type ReligionMetadataCreateReligionData = {
    requestBody: ReligionCreate;
};

export type ReligionMetadataCreateReligionResponse = (ReligionDetailPublic);

export type ReligionMetadataGetReligionByIdData = {
    religionId: string;
};

export type ReligionMetadataGetReligionByIdResponse = (ReligionDetailPublic);

export type ReligionMetadataUpdateReligionData = {
    religionId: string;
    requestBody: ReligionUpdate;
};

export type ReligionMetadataUpdateReligionResponse = (ReligionDetailPublic);

export type ReligionMetadataDeleteReligionData = {
    religionId: string;
};

export type ReligionMetadataDeleteReligionResponse = (unknown);

export type ReligionMetadataGetCategoriesByReligionData = {
    religionId: string;
};

export type ReligionMetadataGetCategoriesByReligionResponse = (unknown);

export type ReligionMetadataGetCategoryByIdData = {
    categoryId: string;
};

export type ReligionMetadataGetCategoryByIdResponse = (ReligionCategoryDetailPublic);

export type ReligionMetadataUpdateCategoryData = {
    categoryId: string;
    requestBody: ReligionCategoryUpdate;
};

export type ReligionMetadataUpdateCategoryResponse = (ReligionCategoryDetailPublic);

export type ReligionMetadataDeleteCategoryData = {
    categoryId: string;
};

export type ReligionMetadataDeleteCategoryResponse = (unknown);

export type ReligionMetadataCreateCategoryData = {
    requestBody: ReligionCategoryCreate;
};

export type ReligionMetadataCreateCategoryResponse = (ReligionCategoryDetailPublic);

export type ReligionMetadataGetSubCategoriesByCategoryData = {
    categoryId: string;
};

export type ReligionMetadataGetSubCategoriesByCategoryResponse = (unknown);

export type ReligionMetadataGetSubCategoryByIdData = {
    subCategoryId: string;
};

export type ReligionMetadataGetSubCategoryByIdResponse = (ReligionSubCategoryDetailPublic);

export type ReligionMetadataUpdateSubCategoryData = {
    requestBody: ReligionSubCategoryUpdate;
    subCategoryId: string;
};

export type ReligionMetadataUpdateSubCategoryResponse = (ReligionSubCategoryDetailPublic);

export type ReligionMetadataDeleteSubCategoryData = {
    subCategoryId: string;
};

export type ReligionMetadataDeleteSubCategoryResponse = (unknown);

export type ReligionMetadataCreateSubCategoryData = {
    requestBody: ReligionSubCategoryCreate;
};

export type ReligionMetadataCreateSubCategoryResponse = (ReligionSubCategoryDetailPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersUpdateUserRoleData = {
    requestBody: UserRoleUpdate;
    userId: string;
};

export type UsersUpdateUserRoleResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsDeleteCacheKeyData = {
    cacheKey: string;
};

export type UtilsDeleteCacheKeyResponse = (Message);

export type UtilsDeleteCachePatternData = {
    pattern: string;
};

export type UtilsDeleteCachePatternResponse = (Message);

export type UtilsClearAllCacheResponse = (Message);