name: Direct Issue
description: Create an issue directly (for project maintainers or contributors)
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in LearningEndToEnd! 🚀

        If you have a question or want to discuss something, please start with a [Question in GitHub Discussions](https://github.com/mkkasana/LearningEndToEnd/discussions/categories/questions) instead.
  - type: checkboxes
    id: direct-issue
    attributes:
      label: Direct Issue
      description: Confirm that this is a bug report or feature request.
      options:
        - label: I have checked existing issues and discussions before creating this.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
