/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUserApprovalsRouteImport } from './routes/_layout/user-approvals'
import { Route as LayoutSupportTicketsRouteImport } from './routes/_layout/support-tickets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutRishteRouteImport } from './routes/_layout/rishte'
import { Route as LayoutRelativesNetworkRouteImport } from './routes/_layout/relatives-network'
import { Route as LayoutLifeEventsRouteImport } from './routes/_layout/life-events'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFindPartnerRouteImport } from './routes/_layout/find-partner'
import { Route as LayoutFamilyTreeRouteImport } from './routes/_layout/family-tree'
import { Route as LayoutFamilyRouteImport } from './routes/_layout/family'
import { Route as LayoutContributionsRouteImport } from './routes/_layout/contributions'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUserApprovalsRoute = LayoutUserApprovalsRouteImport.update({
  id: '/user-approvals',
  path: '/user-approvals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupportTicketsRoute = LayoutSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRishteRoute = LayoutRishteRouteImport.update({
  id: '/rishte',
  path: '/rishte',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRelativesNetworkRoute = LayoutRelativesNetworkRouteImport.update({
  id: '/relatives-network',
  path: '/relatives-network',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLifeEventsRoute = LayoutLifeEventsRouteImport.update({
  id: '/life-events',
  path: '/life-events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFindPartnerRoute = LayoutFindPartnerRouteImport.update({
  id: '/find-partner',
  path: '/find-partner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFamilyTreeRoute = LayoutFamilyTreeRouteImport.update({
  id: '/family-tree',
  path: '/family-tree',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFamilyRoute = LayoutFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContributionsRoute = LayoutContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/contributions': typeof LayoutContributionsRoute
  '/family': typeof LayoutFamilyRoute
  '/family-tree': typeof LayoutFamilyTreeRoute
  '/find-partner': typeof LayoutFindPartnerRoute
  '/items': typeof LayoutItemsRoute
  '/life-events': typeof LayoutLifeEventsRoute
  '/relatives-network': typeof LayoutRelativesNetworkRoute
  '/rishte': typeof LayoutRishteRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/support-tickets': typeof LayoutSupportTicketsRoute
  '/user-approvals': typeof LayoutUserApprovalsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/contributions': typeof LayoutContributionsRoute
  '/family': typeof LayoutFamilyRoute
  '/family-tree': typeof LayoutFamilyTreeRoute
  '/find-partner': typeof LayoutFindPartnerRoute
  '/items': typeof LayoutItemsRoute
  '/life-events': typeof LayoutLifeEventsRoute
  '/relatives-network': typeof LayoutRelativesNetworkRoute
  '/rishte': typeof LayoutRishteRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/support-tickets': typeof LayoutSupportTicketsRoute
  '/user-approvals': typeof LayoutUserApprovalsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/contributions': typeof LayoutContributionsRoute
  '/_layout/family': typeof LayoutFamilyRoute
  '/_layout/family-tree': typeof LayoutFamilyTreeRoute
  '/_layout/find-partner': typeof LayoutFindPartnerRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/life-events': typeof LayoutLifeEventsRoute
  '/_layout/relatives-network': typeof LayoutRelativesNetworkRoute
  '/_layout/rishte': typeof LayoutRishteRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/support-tickets': typeof LayoutSupportTicketsRoute
  '/_layout/user-approvals': typeof LayoutUserApprovalsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/contributions'
    | '/family'
    | '/family-tree'
    | '/find-partner'
    | '/items'
    | '/life-events'
    | '/relatives-network'
    | '/rishte'
    | '/search'
    | '/settings'
    | '/support-tickets'
    | '/user-approvals'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/contributions'
    | '/family'
    | '/family-tree'
    | '/find-partner'
    | '/items'
    | '/life-events'
    | '/relatives-network'
    | '/rishte'
    | '/search'
    | '/settings'
    | '/support-tickets'
    | '/user-approvals'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/contributions'
    | '/_layout/family'
    | '/_layout/family-tree'
    | '/_layout/find-partner'
    | '/_layout/items'
    | '/_layout/life-events'
    | '/_layout/relatives-network'
    | '/_layout/rishte'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/support-tickets'
    | '/_layout/user-approvals'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/user-approvals': {
      id: '/_layout/user-approvals'
      path: '/user-approvals'
      fullPath: '/user-approvals'
      preLoaderRoute: typeof LayoutUserApprovalsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/support-tickets': {
      id: '/_layout/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof LayoutSupportTicketsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rishte': {
      id: '/_layout/rishte'
      path: '/rishte'
      fullPath: '/rishte'
      preLoaderRoute: typeof LayoutRishteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/relatives-network': {
      id: '/_layout/relatives-network'
      path: '/relatives-network'
      fullPath: '/relatives-network'
      preLoaderRoute: typeof LayoutRelativesNetworkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/life-events': {
      id: '/_layout/life-events'
      path: '/life-events'
      fullPath: '/life-events'
      preLoaderRoute: typeof LayoutLifeEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/find-partner': {
      id: '/_layout/find-partner'
      path: '/find-partner'
      fullPath: '/find-partner'
      preLoaderRoute: typeof LayoutFindPartnerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/family-tree': {
      id: '/_layout/family-tree'
      path: '/family-tree'
      fullPath: '/family-tree'
      preLoaderRoute: typeof LayoutFamilyTreeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/family': {
      id: '/_layout/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof LayoutFamilyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contributions': {
      id: '/_layout/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof LayoutContributionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutContributionsRoute: typeof LayoutContributionsRoute
  LayoutFamilyRoute: typeof LayoutFamilyRoute
  LayoutFamilyTreeRoute: typeof LayoutFamilyTreeRoute
  LayoutFindPartnerRoute: typeof LayoutFindPartnerRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLifeEventsRoute: typeof LayoutLifeEventsRoute
  LayoutRelativesNetworkRoute: typeof LayoutRelativesNetworkRoute
  LayoutRishteRoute: typeof LayoutRishteRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSupportTicketsRoute: typeof LayoutSupportTicketsRoute
  LayoutUserApprovalsRoute: typeof LayoutUserApprovalsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutContributionsRoute: LayoutContributionsRoute,
  LayoutFamilyRoute: LayoutFamilyRoute,
  LayoutFamilyTreeRoute: LayoutFamilyTreeRoute,
  LayoutFindPartnerRoute: LayoutFindPartnerRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLifeEventsRoute: LayoutLifeEventsRoute,
  LayoutRelativesNetworkRoute: LayoutRelativesNetworkRoute,
  LayoutRishteRoute: LayoutRishteRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSupportTicketsRoute: LayoutSupportTicketsRoute,
  LayoutUserApprovalsRoute: LayoutUserApprovalsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
